@extends('layouts.app')
@section('title', 'Prise de mesure')
@section('page-title', 'Prise de mesure')

@push('styles')
<link href="{{ asset('assets/css/mesure.css') }}" rel="stylesheet">
<link href="{{ asset('assets/plugins/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet">
<style>
.nav-tabs-elegant{border-bottom:1px solid #e0e0e0;background:linear-gradient(to bottom,#f8f9fa,#fff);border-radius:10px 10px 0 0;padding:0 10px}.nav-tabs-elegant .nav-link{border:none;color:#6c757d;font-weight:500;padding:12px 24px;transition:all .3s ease;position:relative;background:transparent;margin:0 5px}.nav-tabs-elegant .nav-link:hover{color:#007bff;background:rgba(0,123,255,.05);border-radius:8px 8px 0 0}.nav-tabs-elegant .nav-link.active{color:#007bff;background:#fff}.nav-tabs-elegant .nav-link.active:before{content:"";position:absolute;bottom:-1px;left:0;right:0;height:3px;background:linear-gradient(90deg,#007bff,#00c6ff);border-radius:3px}.nav-tabs-elegant .nav-link.disabled{opacity:.5;cursor:not-allowed;color:#adb5bd}.client-row{border:1px solid #ddd;border-radius:8px;padding:12px;background:#fff}.summary-badge{background:#fff;border:1px solid #ddd;border-radius:7px;padding:8px 12px}.required:after{content:" *";color:#dc3545}.measure-label b{font-size:1.05rem}.image-preview-container{cursor:pointer}.image-preview-container img{max-height:300px;object-fit:cover;width:100%}.garment-option{cursor:pointer}.garment-option.active{border-color:#0d6efd!important;background:#f8f9fa}.model-card.selected{border-color:#0d6efd!important;background:#f8f9fa}.added-garments-card{box-shadow:none!important;border:1px solid #dee2e6!important}@media(max-width:768px){.nav-tabs-elegant .nav-link{padding:8px 12px;font-size:12px}}
</style>
@endpush

@section('content')
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3"><div class="breadcrumb-title pe-3">Mesure</div><div class="ps-3"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a></li><li class="breadcrumb-item active">Prise de mesure</li></ol></div></div>

<div class="card">
<div class="instructions p-3 bg-light border-bottom"><h5><i class="bx bx-info-circle me-2"></i>Instructions</h5><p class="mb-0">Remplissez toutes les étapes dans l'ordre. Les champs marqués d'un astérisque sont obligatoires.</p></div>
<ul class="nav nav-tabs nav-tabs-elegant nav-justified" id="wizardTabs">
@foreach([['client','bx-user','Étape 1 : Client'],['photo','bx-camera','Étape 2 : Photo & Modèle'],['measurements','bx-ruler','Étape 3 : Mesures'],['model','bx-closet','Étape 4 : Confirmation']] as $i=>$tab)
<li class="nav-item"><button type="button" class="nav-link {{ $i===0?'active':'disabled' }}" data-step="{{ $tab[0] }}"><i class="bx {{ $tab[1] }} me-1"></i>{{ $tab[2] }}</button></li>
@endforeach
</ul>

<div class="card-body"><form id="clientWizard" action="{{ route('clients.store') }}" method="POST" enctype="multipart/form-data">@csrf
<input type="hidden" name="existing_client_id" id="existingClientId"><input type="hidden" name="mesures_json" id="mesuresJson">

<section class="wizard-pane" data-pane="client">
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2 mb-4"><div class="text-muted">Sélectionnez un client existant pour pré-remplir ses informations et mesures, ou saisissez un nouveau client.</div><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#clientPicker"><i class="bx bx-user-plus me-1"></i>Sélectionner un client existant</button></div>
@if($syntheseMensuelle->isNotEmpty())<div class="d-flex flex-wrap gap-2 bg-light border rounded p-3 mb-3"><strong class="me-2">Synthèse du mois :</strong>@foreach($syntheseMensuelle as $item)<span class="summary-badge"><b>{{ $item['libelle'] }}</b><br><small>Entrée : {{ $item['entrees'] }} habit(s)</small><br><small>Sortie : 0 habit</small></span>@endforeach</div>@endif
<div id="selectedClientAlert" class="alert alert-info d-none justify-content-between align-items-center"><span><strong>Client sélectionné :</strong> <span id="selectedClientText"></span></span><span class="d-flex gap-2"><button type="button" class="btn btn-sm btn-outline-dark" onclick="clearClientSelection()">Effacer la sélection</button><button type="button" class="btn btn-sm btn-outline-secondary" onclick="resetAll()">Tout réinitialiser</button></span></div>
<div class="form-section"><h5 class="border-bottom pb-2 mb-3"><i class="bx bx-user me-2"></i>Informations Générales</h5><div class="row">
<div class="col-md-6 mb-3"><label class="form-label required">Nom</label><input class="form-control" name="nom"></div><div class="col-md-6 mb-3"><label class="form-label required">Prénom</label><input class="form-control" name="prenom"></div>
<div class="col-md-6 mb-3"><label class="form-label">Contact <small class="text-muted">(optionnel)</small></label><input type="tel" class="form-control" name="contact" placeholder="Ex : 76000000"></div><div class="col-md-6 mb-3"><label class="form-label required">Sexe</label><select class="form-select" name="sexe" id="sexe"><option value="">-- Sélectionner --</option><option>Femme</option><option>Homme</option></select></div>
</div></div><div class="text-end"><button type="button" class="btn btn-primary next" data-next="photo">Étape suivante : Photo & Modèle <i class="bx bx-right-arrow-alt ms-2"></i></button></div>
</section>

<section class="wizard-pane d-none" data-pane="photo"><div class="row">
<div class="col-md-6"><div class="d-flex flex-column align-items-center text-center"><div class="image-preview-container mb-3 position-relative" onclick="document.getElementById('modelPhoto').click()"><img id="modelPreview" src="{{ asset('assets/images/model4.jpg') }}" class="img-fluid rounded" alt="Modèle"><div class="overlay-text position-absolute top-50 start-50 translate-middle text-white bg-dark bg-opacity-50 p-2 rounded">Cliquer pour ajouter une photo</div></div><input type="file" id="modelPhoto" class="d-none" accept="image/*"><input type="file" id="modelCamera" class="d-none" accept="image/*" capture="environment"><div class="d-flex flex-wrap gap-2 justify-content-center mb-3"><button type="button" class="btn btn-outline-primary btn-sm" onclick="document.getElementById('modelCamera').click()"><i class="bx bx-camera me-1"></i>Prendre photo du modèle</button></div><div class="mt-3"><div class="form-check form-check-inline"><input class="form-check-input gender-preview" type="radio" name="gender_preview" id="previewFemale" value="Femme" checked><label class="form-check-label" for="previewFemale">Femme</label></div><div class="form-check form-check-inline"><input class="form-check-input gender-preview" type="radio" name="gender_preview" id="previewMale" value="Homme"><label class="form-check-label" for="previewMale">Homme</label></div></div></div></div>
<div class="col-md-6"><div class="existing-models-section"><button type="button" class="btn btn-light w-100 d-flex justify-content-between align-items-center mb-3" onclick="document.getElementById('modelsPanel').classList.toggle('d-none')"><h6 class="mb-0">Choisir un modèle existant</h6><i class="bx bx-chevron-down"></i></button><div id="modelsPanel" class="card card-body p-2"><div class="mb-3"><label class="form-label small">Catégorie:</label><select id="categoryFilter" class="form-select form-select-sm"><option value="all">Toutes les catégories</option><option value="ROBE">Robe</option><option value="JUPE">Jupe</option><option value="HOMME">Vêtement Homme</option><option value="ENFANT">Vêtement Enfant</option><option value="AUTRE">Autre</option></select></div><div class="models-grid" id="modelGrid">@forelse($modeles as $modele)<div class="model-card border rounded p-2" role="button" tabindex="0" data-model-id="{{ $modele->id }}" data-category="{{ $modele->categorie }}"><img src="{{ $modele->photo_path ? asset('storage/'.$modele->photo_path) : asset('assets/images/model1.png') }}" class="img-fluid mb-2 rounded" style="height:80px;width:100%;object-fit:cover" alt="{{ $modele->nom }}"><div class="small text-truncate fw-bold">{{ $modele->nom }}</div>@if($modele->prix)<div class="small text-success">{{ number_format($modele->prix,0,',',' ') }} FCFA</div>@endif</div>@empty<div class="text-center py-3">Aucun modèle trouvé</div>@endforelse</div></div></div></div>
</div><div class="mt-4 d-flex justify-content-between"><button type="button" class="btn btn-secondary prev" data-prev="client">Étape précédente</button><button type="button" class="btn btn-primary next" data-next="measurements">Étape suivante : Mesures</button></div></section>

<section class="wizard-pane d-none" data-pane="measurements">
<div id="femaleOptions" class="form-section mb-4 d-none"><h5 class="border-bottom pb-2 mb-3"><i class="bx bx-closet me-2"></i>Type de vêtement <span class="text-danger">*</span></h5><div class="row"><div class="col-md-6 mb-3"><div class="card p-3 garment-option" data-type="ROBE"><h6><i class="bx bx-closet me-2"></i>Option Robe</h6><p class="small text-muted">Sélectionnez cette option pour les mesures de robe</p><div class="form-check"><input class="form-check-input garment-radio" type="radio" name="femme_type" value="ROBE"><label class="form-check-label">Choisir cette option</label></div></div></div><div class="col-md-6 mb-3"><div class="card p-3 garment-option" data-type="JUPE"><h6><i class="bx bx-closet me-2"></i>Option Jupe</h6><p class="small text-muted">Sélectionnez cette option pour les mesures de jupe</p><div class="form-check"><input class="form-check-input garment-radio" type="radio" name="femme_type" value="JUPE"><label class="form-check-label">Choisir cette option</label></div></div></div></div></div>
@php
$groups=[
'ROBE'=>[['E','Épaule','epaule',1],['M','Manche','manche',1],['P','Poitrine','poitrine',1],['T','Taille','taille',1],['LR','Longueur robe','longueur',1],['F','Fesse','fesse',1],['Tm','Tour de manche','tour_manche',0],['Lp','Longueur de poitrine','longueur_poitrine',0],['Lt','Longueur de taille','longueur_taille',0],['Lf','Longueur de fesse','longueur_fesse',0]],
'JUPE'=>[['E','Épaule','epaule',1],['M','Manche','manche',1],['P','Poitrine','poitrine',1],['T','Taille','taille',1],['L','Longueur','longueur',1],['LJ','Longueur jupe','longueur_jupe',1],['C','Ceinture','ceinture',1],['F','Fesse','fesse',1],['TM','Tour de manche','tour_manche',0],['LP','Longueur de poitrine','longueur_poitrine',0],['Lt','Longueur de taille','longueur_taille',0],['Lf','Longueur de fesse','longueur_fesse',0]],
'HOMME'=>[['E','Épaule','epaule',1],['M','Manche','manche',1],['L','Longueur','longueur',1],['Lp','Longueur pantalon','longueur_pantalon',1],['C','Ceinture','ceinture',1],['Q','Cuisse','cuisse',1],['P','Poitrine','poitrine',0],['Cd','Cou','corps',0],['Tm','Tour de manche','tour_manche',0]]];
@endphp
@foreach($groups as $type=>$fields)<div class="measure-group form-section mb-4 d-none" data-measure-group="{{ $type }}"><h5 class="border-bottom pb-2 mb-3"><i class="bx bx-ruler me-2"></i>Mesures pour {{ ucfirst(strtolower($type)) }}</h5><div class="row">@foreach($fields as [$short,$label,$name,$required])<div class="col-md-6 mb-3"><label class="form-label measure-label {{ $required?'required':'' }}"><b>{{ $short }}</b><br><small class="text-muted">{{ $label }}</small></label><input type="text" inputmode="decimal" class="form-control measure-value" data-field="{{ $name }}" data-required="{{ $required }}"></div>@endforeach</div></div>@endforeach
<div class="mt-4 d-flex justify-content-between"><button type="button" class="btn btn-secondary prev" data-prev="photo">Étape précédente</button><button type="button" class="btn btn-primary next" data-next="model">Étape suivante : Confirmation</button></div>
</section>

<section class="wizard-pane d-none" data-pane="model"><div class="form-section mb-4"><h5 class="border-bottom pb-2 mb-3"><i class="bx bx-tag me-2"></i>Détails du modèle</h5><div class="row">
<div class="col-md-6 mb-3"><label class="form-label">Prix du modèle (FCFA) <small class="text-muted">(optionnel)</small></label><input type="number" min="0" id="price" class="form-control" placeholder="Entrez le prix en FCFA si disponible"></div><div class="col-md-6 mb-3"><label class="form-label">Photo de l'habit (caméra directe) <small class="text-muted">(optionnelle)</small></label><div class="d-flex flex-wrap gap-2"><button type="button" class="btn btn-outline-primary btn-sm" onclick="document.getElementById('habitCamera').click()"><i class="bx bx-camera me-1"></i>Prendre photo directe</button><button type="button" class="btn btn-outline-secondary btn-sm" onclick="document.getElementById('habitPhoto').click()"><i class="bx bx-image me-1"></i>Galerie</button></div><input type="file" id="habitPhoto" class="d-none" accept="image/*"><input type="file" id="habitCamera" class="d-none" accept="image/*" capture="environment"></div>
<div class="col-12 mb-2 mt-2"><h6 class="border-bottom pb-1"><i class="bx bx-money me-2 text-success"></i>Avance reçue</h6></div><div class="col-md-6 mb-3"><label class="form-label">Montant de l'avance (FCFA) <small class="text-muted">(optionnel)</small></label><input type="number" min="0" name="avance" id="avance" class="form-control" placeholder="0" value="0"></div><div class="col-md-6 mb-3"><label class="form-label">Mode de paiement de l'avance</label><select name="avance_moyen" id="avanceMoyen" class="form-select" disabled><option value="ESPECES">Espèces</option><option value="MOBILE_MONEY">Mobile Money</option><option value="VIREMENT">Virement</option><option value="CARTE">Carte Bancaire</option></select></div>
<div class="col-12 mb-3"><label>Description <small class="text-muted">(optionnel)</small></label><textarea id="description" class="form-control" rows="3" placeholder="Ajouter une description ou note pour ce modèle..."></textarea></div><div id="habitPreviewWrap" class="col-12 text-center d-none"><img id="habitPreview" class="img-fluid rounded border" style="max-height:220px"></div>
</div><div class="text-end"><button type="button" id="addGarment" class="btn btn-primary px-4"><i class="bx bx-check-circle me-2"></i>Ajouter ce vêtement au client</button></div></div>
<div id="garmentsCard" class="card mb-4 added-garments-card d-none"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Vêtements ajoutés (<span id="garmentCount">0</span>)</h5><button type="button" class="btn btn-sm btn-outline-primary" onclick="showStep('photo')"><i class="bx bx-plus me-1"></i>Ajouter un autre habit</button></div><div id="garmentList" class="list-group mb-3"></div><div class="text-end" id="totals"></div></div></div>
<div class="mt-4 d-flex justify-content-between"><button type="button" class="btn btn-secondary prev" data-prev="measurements">Étape précédente</button><button type="submit" id="submitButton" class="btn btn-primary px-4"><i class="bx bx-save me-2"></i>Enregistrer le client</button></div>
</section>
</form></div></div>

<div class="modal fade" id="clientPicker" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5>Sélectionner un client existant</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input id="clientSearch" class="form-control mb-3" placeholder="Rechercher par nom, contact ou modèle..."><div id="clientRows" class="d-grid gap-2">@foreach($clientsExistants as $client)<div class="client-row" data-search="{{ Str::lower($client->prenom.' '.$client->nom.' '.$client->contact.' '.$client->mesures->pluck('modele_nom')->join(' ')) }}"><div class="d-flex justify-content-between gap-2"><div><b>{{ $client->prenom }} {{ $client->nom }}</b><div class="small text-muted">{{ $client->contact ?: '—' }} · Modèles enregistrés : {{ $client->mesures->count() }}</div></div><button type="button" class="btn btn-sm btn-primary" onclick="selectClient('{{ $client->id }}')">Utiliser ces informations</button></div></div>@endforeach</div><div id="noClient" class="text-center text-muted py-4 d-none">Aucun client trouvé.</div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button></div></div></div></div>

<div class="modal fade" id="modelPreviewModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5>Détails du modèle</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body text-center"><img id="modalModelImage" class="img-fluid rounded mb-3" style="max-height:400px"><video id="modalModelVideo" class="img-fluid rounded mb-3 d-none" style="max-height:400px" controls></video><h5 id="modalModelName"></h5><p id="modalModelDescription" class="text-muted"></p><div id="modalModelPrice" class="fw-bold text-success"></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button><button type="button" class="btn btn-primary" id="confirmModel">Sélectionner ce modèle</button></div></div></div></div>
<div class="modal fade" id="measurePicker" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Choisir le modèle à préremplir</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>Ce client a plusieurs modèles enregistrés.</p><select id="oldMeasureSelect" class="form-select"></select></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button><button type="button" class="btn btn-primary" id="confirmOldMeasure">Utiliser ce modèle</button></div></div></div></div>
@endsection

@push('scripts')
<script src="{{ asset('assets/plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
<script>
const clients=@json($clientsExistants),models=@json($modeles);let activeStep='client',selectedType='',selectedModel=null,previewModel=null,modelPhotoFile=null,habitPhotoFile=null,existingModelPhoto='',existingHabitPhoto='',pendingClient=null,garments=[];
const qs=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],field=n=>qs(`[name="${n}"]`);
const mediaUrl=p=>p?(`{{ asset('storage') }}/${String(p).replace(/^\/+|storage\//g,'')}`):`{{ asset('assets/images/model1.png') }}`;
const notify=(icon,title,text)=>Swal.fire({icon,title,text,confirmButtonText:'D’accord'});
function showStep(step){if(step!=='client'&&!validClient())return notify('error','Informations incomplètes','Remplissez le nom, le prénom et le sexe.');activeStep=step;all('.wizard-pane').forEach(p=>p.classList.toggle('d-none',p.dataset.pane!==step));all('#wizardTabs .nav-link').forEach(b=>{b.classList.toggle('active',b.dataset.step===step);if(validClient())b.classList.remove('disabled')});}
function validClient(){const existing=qs('#existingClientId').value,required=existing?['prenom','sexe']:['nom','prenom','sexe'];return required.every(n=>String(field(n).value).trim())}
all('.next').forEach(b=>b.onclick=()=>showStep(b.dataset.next));all('.prev').forEach(b=>b.onclick=()=>showStep(b.dataset.prev));all('#wizardTabs .nav-link').forEach(b=>b.onclick=()=>!b.classList.contains('disabled')&&showStep(b.dataset.step));
function setType(type){selectedType=type;all('.garment-option').forEach(x=>x.classList.toggle('active',x.dataset.type===type));all('.garment-radio').forEach(x=>x.checked=x.value===type);all('.measure-group').forEach(x=>x.classList.toggle('d-none',x.dataset.measureGroup!==type));}
all('.garment-option').forEach(x=>x.onclick=()=>setType(x.dataset.type));all('.garment-radio').forEach(x=>x.onclick=e=>{e.stopPropagation();setType(e.target.value)});qs('#sexe').onchange=()=>{const isMan=qs('#sexe').value==='Homme';qs('#previewMale').checked=isMan;qs('#previewFemale').checked=!isMan;if(!modelPhotoFile&&!selectedModel&&!existingModelPhoto)qs('#modelPreview').src=isMan?`{{ asset('assets/images/model3.jpg') }}`:`{{ asset('assets/images/model4.jpg') }}`;if(isMan){setType('HOMME');qs('#femaleOptions').classList.add('d-none')}else{qs('#femaleOptions').classList.remove('d-none');if(selectedType==='HOMME')setType('')}};
all('.gender-preview').forEach(radio=>radio.onchange=e=>{if(!modelPhotoFile&&!selectedModel&&!existingModelPhoto)qs('#modelPreview').src=e.target.value==='Homme'?`{{ asset('assets/images/model3.jpg') }}`:`{{ asset('assets/images/model4.jpg') }}`});
function readFile(input,preview,callback){const f=input.files[0];if(!f)return;callback(f);preview.src=URL.createObjectURL(f);preview.closest('.d-none')?.classList.remove('d-none')}
qs('#modelPhoto').onchange=()=>readFile(qs('#modelPhoto'),qs('#modelPreview'),f=>{modelPhotoFile=f;selectedModel=null;markModel()});qs('#modelCamera').onchange=()=>readFile(qs('#modelCamera'),qs('#modelPreview'),f=>{modelPhotoFile=f;selectedModel=null;markModel()});qs('#habitPhoto').onchange=()=>readFile(qs('#habitPhoto'),qs('#habitPreview'),f=>habitPhotoFile=f);qs('#habitCamera').onchange=()=>readFile(qs('#habitCamera'),qs('#habitPreview'),f=>habitPhotoFile=f);
function markModel(){all('.model-card').forEach(c=>c.classList.toggle('selected',selectedModel&&String(c.dataset.modelId)===String(selectedModel.id)))}
all('.model-card').forEach(c=>c.onclick=()=>{previewModel=models.find(m=>String(m.id)===String(c.dataset.modelId));if(!previewModel)return;const hasVideo=!!previewModel.video_path;qs('#modalModelImage').classList.toggle('d-none',hasVideo);qs('#modalModelVideo').classList.toggle('d-none',!hasVideo);qs('#modalModelImage').src=mediaUrl(previewModel.photo_path);qs('#modalModelVideo').src=hasVideo?mediaUrl(previewModel.video_path):'';qs('#modalModelName').textContent=previewModel.nom||'';qs('#modalModelDescription').textContent=previewModel.description||'Aucune description';qs('#modalModelPrice').textContent=previewModel.prix?`${Number(previewModel.prix).toLocaleString('fr-FR')} FCFA`:'';new bootstrap.Modal(qs('#modelPreviewModal')).show()});
qs('#confirmModel').onclick=()=>{selectedModel=previewModel;modelPhotoFile=null;existingModelPhoto='';qs('#modelPreview').src=mediaUrl(selectedModel.photo_path);if(selectedModel.prix)qs('#price').value=selectedModel.prix;markModel();bootstrap.Modal.getInstance(qs('#modelPreviewModal'))?.hide();Swal.fire({icon:'success',title:'Modèle sélectionné',text:`Modèle "${selectedModel.nom}" sélectionné`,timer:1800,showConfirmButton:false,toast:true,position:'top-end'})};
qs('#categoryFilter').onchange=e=>all('.model-card').forEach(c=>c.classList.toggle('d-none',e.target.value!=='all'&&c.dataset.category!==e.target.value));
function measurePayload(){const p={sexe:field('sexe').value,typeVetement:selectedType,selectedModelId:selectedModel?.id||'',modeleNom:selectedModel?.nom||''};all(`[data-measure-group="${selectedType}"] .measure-value`).forEach(i=>p[`${selectedType.toLowerCase()}_${i.dataset.field}`]=i.value);return p}
function validateGarment(){if(!validClient())return 'Informations du client incomplètes.';if(!selectedType)return 'Choisissez le type de vêtement.';const missing=all(`[data-measure-group="${selectedType}"] [data-required="1"]`).some(i=>!i.value.trim());return missing?'Remplissez toutes les mesures obligatoires.':''}
qs('#addGarment').onclick=()=>{const error=validateGarment();if(error)return notify('error','Erreur de validation',error);garments.push({...measurePayload(),prix:qs('#price').value,description:qs('#description').value,modelPhotoFile,habitPhotoFile,existing_photo_path:modelPhotoFile?'':existingModelPhoto||selectedModel?.photo_path||'',existing_habit_photo_path:habitPhotoFile?'':existingHabitPhoto});renderGarments();resetGarment();Swal.fire({icon:'success',title:'Vêtement ajouté',text:'Le vêtement a été ajouté au client.',timer:1800,showConfirmButton:false,toast:true,position:'top-end'})};
function resetGarment(){selectedModel=null;modelPhotoFile=null;habitPhotoFile=null;existingModelPhoto='';existingHabitPhoto='';qs('#price').value='';qs('#description').value='';qs('#modelPhoto').value='';qs('#habitPhoto').value='';qs('#modelPreview').src=field('sexe').value==='Homme'?`{{ asset('assets/images/model3.jpg') }}`:`{{ asset('assets/images/model4.jpg') }}`;qs('#habitPreviewWrap').classList.add('d-none');all('.measure-value').forEach(i=>i.value='');markModel();showStep('client')}
function renderGarments(){const list=qs('#garmentList');list.innerHTML='';garments.forEach((g,i)=>{const row=document.createElement('div');row.className='list-group-item d-flex justify-content-between align-items-start';row.innerHTML=`<div><b>${g.modeleNom||`Modèle ${i+1}`}</b><div class="small text-muted">${g.typeVetement} · ${g.sexe}</div><div class="small text-success">${g.prix?Number(g.prix).toLocaleString('fr-FR')+' FCFA':'Prix à définir'}</div></div><button type="button" class="btn btn-sm btn-outline-danger">Supprimer</button>`;row.querySelector('button').onclick=()=>{garments.splice(i,1);renderGarments()};list.appendChild(row)});qs('#garmentCount').textContent=garments.length;qs('#garmentsCard').classList.toggle('d-none',!garments.length);const total=garments.reduce((s,g)=>s+Number(g.prix||0),0),avance=Number(qs('#avance').value||0);qs('#totals').innerHTML=`<b>Total : ${total.toLocaleString('fr-FR')} FCFA</b>${avance?`<br><span class="text-success"><b>Avance :</b> ${avance.toLocaleString('fr-FR')} FCFA</span><br><span class="text-danger"><b>Reste :</b> ${(total-avance).toLocaleString('fr-FR')} FCFA</span>`:''}`}
qs('#avance').oninput=()=>{qs('#avanceMoyen').disabled=Number(qs('#avance').value||0)<=0;renderGarments()};
function mapOldMeasure(m){setType((m.type_vetement||'').toUpperCase());field('sexe').value=m.sexe||field('sexe').value;qs('#previewMale').checked=field('sexe').value==='Homme';qs('#previewFemale').checked=field('sexe').value!=='Homme';qs('#femaleOptions').classList.toggle('d-none',field('sexe').value!=='Femme');all('.measure-value').forEach(i=>i.value='');all(`[data-measure-group="${selectedType}"] .measure-value`).forEach(i=>i.value=m[i.dataset.field]??'');selectedModel=models.find(x=>String(x.id)===String(m.modele_reference_id))||null;existingModelPhoto=m.photo_path||'';existingHabitPhoto=m.habit_photo_path||'';qs('#modelPreview').src=mediaUrl(existingModelPhoto||selectedModel?.photo_path);qs('#price').value=m.prix||'';qs('#description').value=m.description||'';if(existingHabitPhoto){qs('#habitPreview').src=mediaUrl(existingHabitPhoto);qs('#habitPreviewWrap').classList.remove('d-none')}qs('#selectedClientText').dataset.lastMeasure=`Dernière mesure le ${m.date_mesure?new Date(m.date_mesure).toLocaleDateString('fr-FR'):'date inconnue'} · ${m.type_vetement||''}`;renderSelectedClientText();markModel()}
function renderSelectedClientText(){if(!pendingClient)return;const last=qs('#selectedClientText').dataset.lastMeasure||'';qs('#selectedClientText').textContent=`${pendingClient.prenom||''} ${pendingClient.nom||''} · ${pendingClient.contact||''}${last?' · '+last:''}`}
function selectClient(id){const c=clients.find(x=>String(x.id)===String(id));if(!c)return;pendingClient=c;qs('#selectedClientText').dataset.lastMeasure='';qs('#existingClientId').value=c.id;field('nom').value=c.nom||'';field('prenom').value=c.prenom||'';field('contact').value=String(c.contact||'').replace(/\D/g,'').slice(-8);field('sexe').value=c.sexe||c.mesures?.[0]?.sexe||'';renderSelectedClientText();qs('#selectedClientAlert').classList.remove('d-none');qs('#selectedClientAlert').classList.add('d-flex');qs('#femaleOptions').classList.toggle('d-none',field('sexe').value!=='Femme');bootstrap.Modal.getInstance(qs('#clientPicker'))?.hide();if(c.mesures?.length===1)mapOldMeasure(c.mesures[0]);else if(c.mesures?.length>1){qs('#oldMeasureSelect').innerHTML=c.mesures.map((m,i)=>`<option value="${i}">${m.modele_nom||m.type_vetement} - ${m.date_mesure?new Date(m.date_mesure).toLocaleDateString('fr-FR'):'Date inconnue'}</option>`).join('');new bootstrap.Modal(qs('#measurePicker')).show()}}
qs('#confirmOldMeasure').onclick=()=>{if(pendingClient)mapOldMeasure(pendingClient.mesures[Number(qs('#oldMeasureSelect').value)]);bootstrap.Modal.getInstance(qs('#measurePicker'))?.hide()};
function clearClientSelection(){qs('#existingClientId').value='';qs('#selectedClientAlert').classList.add('d-none');qs('#selectedClientAlert').classList.remove('d-flex')}
function resetAll(){field('nom').value=field('prenom').value=field('contact').value=field('sexe').value='';qs('#existingClientId').value='';qs('#selectedClientAlert').classList.add('d-none');garments=[];renderGarments();setType('');resetGarment()}
qs('#clientSearch').oninput=e=>{let count=0;all('.client-row').forEach(r=>{const show=r.dataset.search.includes(e.target.value.toLowerCase());r.classList.toggle('d-none',!show);if(show)count++});qs('#noClient').classList.toggle('d-none',count>0)};
qs('#clientWizard').onsubmit=async e=>{e.preventDefault();if(!garments.length)return notify('warning','Vêtement requis',"Ajoutez au moins un vêtement avant l'enregistrement.");const button=qs('#submitButton');button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Enregistrement...';const data=new FormData(e.target),payload=[];garments.forEach((g,i)=>{const item={...g};delete item.modelPhotoFile;delete item.habitPhotoFile;payload.push(item);if(g.modelPhotoFile)data.append(`model_photos[${i}]`,g.modelPhotoFile);if(g.habitPhotoFile)data.append(`habit_photos[${i}]`,g.habitPhotoFile)});data.set('mesures_json',JSON.stringify(payload));try{const response=await fetch(e.target.action,{method:'POST',body:data,headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}}),json=await response.json();if(!response.ok)throw new Error(json.message||Object.values(json.errors||{}).flat().join('\n'));await Swal.fire({icon:'success',title:'Client enregistré !',text:json.message,timer:2200,showConfirmButton:false});window.location.href=json.redirect}catch(error){notify('error','Erreur',error.message);button.disabled=false;button.innerHTML='<i class="bx bx-save me-2"></i>Enregistrer le client'}};
</script>
@endpush
