@extends('layouts.app')
@section('title', 'Clients')
@section('page-title', 'Clients')

@push('styles')
<link href="{{ asset('assets/css/mesure.css') }}" rel="stylesheet">
<link href="{{ asset('assets/plugins/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet">
<style>
.client-detail-media{max-width:45%}.client-detail-scroll{overflow-y:auto;max-height:560px}.model-preview-card img{width:100%;height:auto;max-height:160px;object-fit:cover}.edit-model-item.active .text-muted{color:rgba(255,255,255,.8)!important}.edit-photo{max-height:300px;width:100%;object-fit:cover}.edit-habit-photo{max-height:220px;object-fit:cover}@media(max-width:767px){.client-detail-content{flex-direction:column!important}.client-detail-media{max-width:100%;width:100%}.client-detail-scroll{max-height:none}}
</style>
@endpush

@section('content')
<div class="page-header"><div class="container-fluid"><div class="page-breadcrumb d-flex flex-wrap align-items-center gap-2 mb-3"><div class="breadcrumb-title pe-3">Clients</div><div class="ps-3"><nav><ol class="breadcrumb mb-0 p-0"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a></li><li class="breadcrumb-item active">Liste des clients</li></ol></nav></div>@if(!Auth::user()->isTailleur())<div class="ms-auto"><a href="{{ route('clients.create') }}" class="btn btn-primary">Ajouter un client</a></div>@endif</div></div></div>

<div class="card"><div class="card-body">
@if(Auth::user()->isTailleur())
<div class="alert alert-info py-2 mb-3"><i class="bx bx-info-circle me-1"></i>Vous voyez uniquement les clients dont un modèle vous est affecté.</div>
@endif
<div class="row g-3 align-items-center mb-3"><div class="col-md-6 col-lg-5"><label class="form-label">Filtrer la liste</label><input type="text" id="clientTableSearch" class="form-control" placeholder="Rechercher par nom, contact, sexe ou modèle..."></div></div>
<div class="table-responsive"><table class="table table-striped table-bordered align-middle mb-0" style="width:100%"><thead class="table-light"><tr><th style="width:60px">N</th><th>Prénom</th><th>Nom</th><th>Contact</th><th>Sexe/Modèle</th><th>Action</th></tr></thead><tbody id="clientTableBody">
@forelse($clients as $index=>$client)
@php $mesure=$client->mesures->first(); @endphp
<tr class="client-table-row" data-search="{{ Str::lower($client->prenom.' '.$client->nom.' '.$client->contact.' '.$client->sexe.' '.$client->mesures->pluck('modele_nom')->join(' ').' '.$client->mesures->pluck('type_vetement')->join(' ')) }}"><td class="fw-semibold text-muted">{{ $index+1 }}</td><td>{{ $client->prenom }}</td><td>{{ $client->nom }}</td><td>{{ $client->contact }}</td><td>{{ $mesure?->sexe ?: $client->sexe }}@if($mesure?->type_vetement)<br><small class="text-muted">{{ $mesure->type_vetement }}</small>@endif<br><small class="text-muted">{{ $client->mesures->count() }} modèle(s)</small></td><td><button class="btn btn-sm btn-info me-1" onclick="openClientDetail('{{ $client->id }}')" title="Détail"><i class="bx bx-show"></i></button>@if(!Auth::user()->isTailleur())<button class="btn btn-sm btn-warning me-1" onclick="openClientEdit('{{ $client->id }}')" title="Modifier"><i class="bx bx-pencil"></i></button><button class="btn btn-sm btn-danger" onclick="deleteClient('{{ $client->id }}')" title="Supprimer"><i class="bx bx-trash"></i></button>@endif</td></tr>
@empty<tr id="emptyClients"><td colspan="6" class="text-center">Aucun client trouvé</td></tr>@endforelse
<tr id="noFilteredClients" class="d-none"><td colspan="6" class="text-center">Aucun client trouvé</td></tr>
</tbody></table></div></div></div>

<div class="modal fade" id="clientDetailModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content client-detail-content d-flex flex-row"><div id="detailMedia" class="client-detail-media flex-shrink-0 p-3"></div><div class="modal-body client-detail-scroll flex-grow-1 p-3"><div class="d-flex justify-content-between mb-3"><h5 id="detailClientName"></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div id="detailContent"></div></div></div></div></div>

<div class="modal fade" id="clientEditModal" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><div class="modal-header bg-primary text-white"><h5 class="modal-title">Modification du Client</h5><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row">
<div class="col-md-4 text-center"><div class="image-preview-container mb-3" onclick="document.getElementById('editModelPhoto').click()"><img id="editPhotoPreview" class="img-fluid rounded edit-photo" alt="Preview"><div class="mt-2 text-muted small">Cliquer pour modifier la photo</div></div><input type="file" id="editModelPhoto" class="d-none" accept="image/*"><div class="mt-3"><div class="form-check form-check-inline"><input class="form-check-input edit-sex" type="radio" name="edit_sexe" value="Femme"><label class="form-check-label">Femme</label></div><div class="form-check form-check-inline"><input class="form-check-input edit-sex" type="radio" name="edit_sexe" value="Homme"><label class="form-check-label">Homme</label></div></div><div class="mt-4 text-start"><h6 class="fw-bold">Photo de l'habit à coudre</h6><div class="border rounded p-2 text-center bg-light"><img id="editHabitPreview" class="img-fluid rounded edit-habit-photo d-none"><div id="noEditHabit" class="text-muted small">Aucune photo enregistrée</div></div><div class="d-flex gap-2 mt-2"><button type="button" class="btn btn-sm btn-outline-primary flex-grow-1" onclick="document.getElementById('editHabitPhoto').click()">Ajouter ou modifier la photo</button></div><input type="file" id="editHabitPhoto" class="d-none" accept="image/*"></div></div>
<div class="col-md-8"><h5 class="mb-3"><i class="bx bx-user"></i> Informations Générales</h5><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Nom <span class="text-danger">*</span></label><input id="editNom" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Prénom <span class="text-danger">*</span></label><input id="editPrenom" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Contact <small class="text-muted">(optionnel)</small></label><input id="editContact" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Prix (FCFA)</label><input id="editPrix" type="number" min="0" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Nom du modèle <span class="text-danger">*</span></label><input id="editModeleNom" class="form-control" placeholder="Ex: Grand boubou, Jupe droite..."></div><div class="col-md-12 mb-3"><label class="form-label">Description</label><textarea id="editDescription" class="form-control" rows="3"></textarea></div></div>
<div class="mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0"><i class="bx bx-list-ul"></i> Modèles du client</h5><div class="d-flex gap-2"><button type="button" class="btn btn-sm btn-outline-primary" onclick="startNewEditMeasure()"><i class="bx bx-plus me-1"></i>Nouveau modèle</button><button type="button" id="deleteEditMeasure" class="btn btn-sm btn-outline-danger" onclick="deleteCurrentMeasure()"><i class="bx bx-trash me-1"></i>Supprimer</button></div></div><div id="newMeasureNotice" class="alert alert-info py-2 d-none">Nouveau modèle en cours de création. Les mesures du modèle sélectionné ont été conservées.</div><div id="editModelsList" class="list-group"></div></div>
<div id="editFemaleTypes" class="mb-4 d-none"><h5 class="mb-3"><i class="bx bx-closet"></i> Type de vêtement</h5><div class="row"><div class="col-md-6"><div class="card p-3 edit-type" data-type="ROBE" role="button"><h6><i class="bx bx-female"></i> Option Robe</h6></div></div><div class="col-md-6"><div class="card p-3 edit-type" data-type="JUPE" role="button"><h6><i class="bx bx-female"></i> Option Jupe</h6></div></div></div></div>
<h5 class="mb-3"><i class="bx bx-ruler"></i> Mesures</h5><div class="row" id="editMeasureFields">@php $editFields=['epaule'=>'Épaule','manche'=>'Manche','poitrine'=>'Poitrine','taille'=>'Taille','longueur'=>'Longueur','fesse'=>'Fesse','tour_manche'=>'Tour de manche','longueur_poitrine'=>'Longueur poitrine','longueur_taille'=>'Longueur taille','longueur_fesse'=>'Longueur fesse','longueur_jupe'=>'Longueur Jupe','ceinture'=>'Ceinture','longueur_pantalon'=>'Longueur Pantalon','cuisse'=>'Cuisse','corps'=>'Cou']; @endphp @foreach($editFields as $name=>$label)<div class="col-md-6 mb-3 edit-measure-field" data-field="{{ $name }}"><label class="form-label">{{ $label }}</label><input class="form-control" inputmode="decimal" data-edit-measure="{{ $name }}"></div>@endforeach</div>
</div></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button><button id="saveClientEdit" class="btn btn-primary" onclick="saveClientEdit()">Enregistrer</button></div></div></div></div>
@endsection

@push('scripts')
<script src="{{ asset('assets/plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
<script>
let editingClient=null,editingMeasure=null,isCreatingMeasure=false,editModelPhoto=null,editHabitPhoto=null;
const qs=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const storageUrl=p=>p?`{{ asset('storage') }}/${String(p).replace(/^\/+|storage\//g,'')}`:null;
const sortedMeasures=c=>[...(c?.mesures||[])].sort((a,b)=>new Date(b.date_mesure||0)-new Date(a.date_mesure||0));
const modelName=(m,i)=>m?.modele_nom?.trim()||`Modèle #${i+1}`;
const modelImage=m=>storageUrl(m?.photo_path)||(m?.sexe==='Homme'?`{{ asset('assets/images/model3.jpg') }}`:`{{ asset('assets/images/model4.jpg') }}`);
async function request(url,data=null){const response=await fetch(url,{method:data?'POST':'GET',body:data||undefined,headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}}),json=await response.json();if(!response.ok)throw new Error(json.message||Object.values(json.errors||{}).flat().join('\n'));return json}
qs('#clientTableSearch').oninput=e=>{let shown=0;all('.client-table-row').forEach(row=>{const visible=row.dataset.search.includes(e.target.value.toLowerCase());row.classList.toggle('d-none',!visible);if(visible)shown++});qs('#noFilteredClients').classList.toggle('d-none',shown>0)};
async function openClientDetail(id){try{qs('#detailClientName').textContent='Chargement...';qs('#detailContent').innerHTML='<div class="text-center py-4"><div class="spinner-border text-primary"></div></div>';qs('#detailMedia').innerHTML='';new bootstrap.Modal(qs('#clientDetailModal')).show();const{client:c}=await request(`{{ url('/clients') }}/${id}`);const ms=sortedMeasures(c);qs('#detailClientName').textContent=`${c.prenom||''} ${c.nom||''}`;qs('#detailMedia').innerHTML=ms.length?ms.map((m,i)=>`<div class="border rounded p-2 mb-2 model-preview-card"><div class="small fw-bold mb-2 text-truncate">${modelName(m,i)}</div><img src="${modelImage(m)}" class="img-fluid rounded"></div>`).join(''):`<img src="${modelImage(null)}" class="img-fluid rounded">`;const total=ms.reduce((s,m)=>s+Number(m.prix||0),0);qs('#detailContent').innerHTML=ms.length?`<div class="alert alert-secondary mb-3"><div class="d-flex justify-content-between"><strong>${ms.length} modèle(s)</strong><strong>Total: ${total.toLocaleString('fr-FR')} FCFA</strong></div></div>`+ms.map((m,i)=>measureDetail(m,i)).join(''):'<div class="alert alert-info">Aucune mesure disponible</div>'}catch(e){qs('#detailContent').innerHTML=`<div class="alert alert-danger">Erreur : ${e.message}</div>`}}
function measureDetail(m,i){const labels={epaule:'Épaule',manche:'Manche',poitrine:'Poitrine',taille:'Taille',longueur:'Longueur',fesse:'Fesse',tour_manche:'Tour de manche',longueur_poitrine:'Longueur poitrine',longueur_taille:'Longueur taille',longueur_fesse:'Longueur fesse',longueur_jupe:'Longueur Jupe',ceinture:'Ceinture',longueur_pantalon:'Longueur Pantalon',cuisse:'Cuisse',corps:'Cou'};let rows=Object.entries(labels).filter(([k])=>m[k]!==null&&m[k]!==''&&m[k]!==undefined).map(([k,l])=>`<li class="list-group-item d-flex justify-content-between"><span>${l}</span><b>${m[k]}</b></li>`).join('');return `<ul class="list-group mb-3"><li class="list-group-item fw-bold bg-light"><div class="d-flex justify-content-between"><span>${modelName(m,i)}</span><span>${m.sexe||''} ${m.type_vetement?'• '+m.type_vetement:''}</span></div></li>${m.prix?`<li class="list-group-item fw-bold bg-success text-white d-flex justify-content-between"><span>Prix du modèle:</span><span class="badge bg-light text-dark fs-6">${Number(m.prix).toLocaleString('fr-FR')} FCFA</span></li>`:''}<li class="list-group-item"><b>Description:</b><p class="text-muted small mb-0">${m.description||'Aucune description fournie'}</p></li>${rows}${m.habit_photo_path?`<li class="list-group-item"><b>Photo de l'habit:</b><div class="mt-2 text-center"><img src="${storageUrl(m.habit_photo_path)}" class="img-fluid" style="max-width:200px"></div></li>`:''}</ul>`}
async function openClientEdit(id){try{new bootstrap.Modal(qs('#clientEditModal')).show();qs('#editNom').value='';qs('#editPrenom').value='';qs('#editContact').value='';qs('#editModelsList').innerHTML='<div class="text-center py-3"><div class="spinner-border text-primary spinner-border-sm"></div> Chargement...</div>';const{client}=await request(`{{ url('/clients') }}/${id}`);editingClient=client;qs('#editNom').value=client.nom||'';qs('#editPrenom').value=client.prenom||'';qs('#editContact').value=client.contact||'';renderEditModels();selectEditMeasure(0)}catch(e){Swal.fire('Erreur',e.message||'Impossible de charger le client','error');bootstrap.Modal.getInstance(qs('#clientEditModal'))?.hide()}}
function renderEditModels(){const ms=sortedMeasures(editingClient);qs('#editModelsList').innerHTML=ms.length?ms.map((m,i)=>`<button type="button" class="list-group-item list-group-item-action edit-model-item ${!isCreatingMeasure&&editingMeasure?.id===m.id?'active':''}" onclick="selectEditMeasure(${i})"><div class="d-flex justify-content-between"><div><b>${modelName(m,i)}</b><div class="small text-muted">${m.sexe||''} ${m.type_vetement?'• '+m.type_vetement:''}</div></div><span class="badge bg-secondary rounded-pill">${m.prix||0} FCFA</span></div></button>`).join(''):'<p class="text-muted small p-2 mb-0">Aucun modèle — cliquez sur <b>Nouveau modèle</b> pour en créer un.</p>'}
function selectEditMeasure(index){const ms=sortedMeasures(editingClient);editingMeasure=ms[index]||null;isCreatingMeasure=false;qs('#newMeasureNotice').classList.add('d-none');qs('#deleteEditMeasure').classList.toggle('d-none',!editingMeasure);fillEditMeasure(editingMeasure||{sexe:editingClient.sexe||'Femme'});renderEditModels()}
function fillEditMeasure(m){const sexe=m.sexe||editingClient.sexe||'Femme';all('.edit-sex').forEach(r=>r.checked=r.value===sexe);qs('#editFemaleTypes').classList.toggle('d-none',sexe!=='Femme');qs('#editPrix').value=m.prix||'';qs('#editModeleNom').value=m.modele_nom||'';qs('#editDescription').value=m.description||'';editModelPhoto=editHabitPhoto=null;qs('#editPhotoPreview').src=modelImage(m);const habit=storageUrl(m.habit_photo_path);qs('#editHabitPreview').src=habit||'';qs('#editHabitPreview').classList.toggle('d-none',!habit);qs('#noEditHabit').classList.toggle('d-none',!!habit);all('[data-edit-measure]').forEach(input=>input.value=m[input.dataset.editMeasure]??'');setEditType((m.type_vetement||'').toUpperCase()||(sexe==='Homme'?'HOMME':''),false)}
function startNewEditMeasure(){const base=editingMeasure||{};editingMeasure=null;isCreatingMeasure=true;qs('#newMeasureNotice').classList.remove('d-none');qs('#deleteEditMeasure').classList.add('d-none');fillEditMeasure({...base,id:null,prix:'',modele_nom:'',description:'',photo_path:null,habit_photo_path:null});renderEditModels()}
const editSets={ROBE:['epaule','manche','poitrine','taille','longueur','fesse','tour_manche','longueur_poitrine','longueur_taille','longueur_fesse'],JUPE:['epaule','manche','poitrine','taille','longueur','longueur_jupe','ceinture','fesse','tour_manche','longueur_poitrine','longueur_taille','longueur_fesse'],HOMME:['epaule','manche','longueur','longueur_pantalon','ceinture','cuisse','poitrine','corps','tour_manche']};let editType='';
function setEditType(type,update=true){editType=type;all('.edit-type').forEach(c=>c.classList.toggle('border-primary',c.dataset.type===type));all('.edit-type').forEach(c=>c.classList.toggle('bg-light',c.dataset.type===type));all('.edit-measure-field').forEach(x=>x.classList.toggle('d-none',!(editSets[type]||[]).includes(x.dataset.field)));if(update&&type==='HOMME')all('.edit-sex').forEach(r=>r.checked=r.value==='Homme')}
all('.edit-type').forEach(c=>c.onclick=()=>setEditType(c.dataset.type));all('.edit-sex').forEach(r=>r.onchange=e=>{const femme=e.target.value==='Femme';qs('#editFemaleTypes').classList.toggle('d-none',!femme);setEditType(femme?(editType==='JUPE'?'JUPE':'ROBE'):'HOMME')});
qs('#editModelPhoto').onchange=e=>{editModelPhoto=e.target.files[0]||null;if(editModelPhoto)qs('#editPhotoPreview').src=URL.createObjectURL(editModelPhoto)};qs('#editHabitPhoto').onchange=e=>{editHabitPhoto=e.target.files[0]||null;if(editHabitPhoto){qs('#editHabitPreview').src=URL.createObjectURL(editHabitPhoto);qs('#editHabitPreview').classList.remove('d-none');qs('#noEditHabit').classList.add('d-none')}};
async function saveClientEdit(){const nom=qs('#editNom').value.trim(),prenom=qs('#editPrenom').value.trim(),contact=qs('#editContact').value.trim(),sexe=all('.edit-sex').find(r=>r.checked)?.value;if(!nom||!prenom||!sexe)return Swal.fire('Erreur','Nom, Prénom et Sexe sont obligatoires.','error');const button=qs('#saveClientEdit');button.disabled=true;try{const info=new FormData();info.append('_method','PUT');info.append('nom',nom);info.append('prenom',prenom);info.append('contact',contact);info.append('sexe',sexe);await request(`{{ url('/clients') }}/${editingClient.id}`,info);if(editType){const modeleNom=qs('#editModeleNom').value.trim();if(!modeleNom){button.disabled=false;return Swal.fire('Erreur','Veuillez nommer le modèle.','error')}const data=new FormData();data.append('sexe',sexe);data.append('type_vetement',editType);data.append('prix',qs('#editPrix').value);data.append('modele_nom',modeleNom);data.append('description',qs('#editDescription').value);all('[data-edit-measure]').forEach(i=>{if(!i.closest('.d-none'))data.append(i.dataset.editMeasure,i.value)});if(editModelPhoto)data.append('photo',editModelPhoto);if(editHabitPhoto)data.append('habitPhoto',editHabitPhoto);const isNew=isCreatingMeasure||!editingMeasure;if(!isNew)data.append('_method','PUT');const endpoint=isNew?`{{ url('/clients') }}/${editingClient.id}/mesures`:`{{ url('/clients') }}/${editingClient.id}/mesures/${editingMeasure.id}`;const result=await request(endpoint,data);await Swal.fire({icon:'success',title:'Succès',text:result.message,timer:1800,showConfirmButton:false})}else{await Swal.fire({icon:'success',title:'Client mis à jour',timer:1500,showConfirmButton:false})}window.location.reload()}catch(error){Swal.fire('Erreur',error.message||'Une erreur est survenue','error');button.disabled=false}}
async function deleteClient(id){const result=await Swal.fire({title:'Supprimer ce client ?',text:'Toutes ses mesures seront supprimées.',icon:'warning',showCancelButton:true,confirmButtonColor:'#d33',confirmButtonText:'Oui, supprimer !',cancelButtonText:'Annuler'});if(!result.isConfirmed)return;try{const data=new FormData();data.append('_method','DELETE');await request(`{{ url('/clients') }}/${id}`,data);await Swal.fire({icon:'success',title:'Supprimé !',timer:1500,showConfirmButton:false});window.location.reload()}catch(e){Swal.fire('Erreur',e.message||'Impossible de supprimer le client','error')}}
async function deleteCurrentMeasure(){if(!editingClient||!editingMeasure)return;const result=await Swal.fire({title:'Supprimer ce modèle ?',icon:'warning',showCancelButton:true,confirmButtonText:'Supprimer',cancelButtonText:'Annuler',confirmButtonColor:'#d33'});if(!result.isConfirmed)return;try{const data=new FormData();data.append('_method','DELETE');await request(`{{ url('/clients') }}/${editingClient.id}/mesures/${editingMeasure.id}`,data);await Swal.fire({icon:'success',title:'Modèle supprimé',timer:1500,showConfirmButton:false});window.location.reload()}catch(e){Swal.fire('Erreur',e.message||'Erreur lors de la suppression','error')}}
</script>
@endpush
