@extends('layouts.app')
@section('title','Albums')
@section('page-title','Albums')
@push('styles')<style>.modele-card{transition:.3s;overflow:hidden}.modele-card:hover{transform:translateY(-3px);box-shadow:0 .5rem 1rem rgba(0,0,0,.15)}.modele-photo-container{position:relative;overflow:hidden;height:500px;background:#f0f0f0}.modele-photo{width:100%;height:100%;object-fit:cover;transition:transform .3s}.modele-card:hover .modele-photo{transform:scale(1.025)}.modele-actions{position:absolute;top:10px;right:10px;opacity:0;transform:translateY(-10px);transition:.3s;display:flex;gap:5px}.modele-photo-container:hover .modele-actions{opacity:1;transform:none}@media(max-width:768px){.modele-photo-container{height:360px}.modele-actions{opacity:1;transform:none}}</style>@endpush
@section('content')
<div class="page-breadcrumb d-flex flex-wrap align-items-center gap-2 mb-3"><div class="breadcrumb-title pe-3">Albums</div><div class="ps-3"><ol class="breadcrumb mb-0 p-0"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a></li><li class="breadcrumb-item active">Gestion des modèles</li></ol></div><a href="{{ route('modeles.create') }}" class="btn btn-primary ms-auto"><i class="bx bx-plus me-1"></i>Nouveau Modèle</a></div>
<form method="GET" id="modelesFilterForm" class="mb-4">
    <div class="row g-2 align-items-center mb-2">
        <div class="col"><div class="input-group"><span class="input-group-text bg-light border-end-0"><i class="bx bx-search"></i></span><input name="search" class="form-control border-start-0" placeholder="Rechercher un modèle..." value="{{ request('search') }}" oninput="debounceSubmit()"></div></div>
    </div>
    <div class="d-flex flex-wrap gap-2">
        @php $catLabels=[''=>'Tous','ROBE'=>'Robes','JUPE'=>'Jupes','HOMME'=>'Homme','ENFANT'=>'Enfant','AUTRE'=>'Autre']; @endphp
        @foreach($catLabels as $val=>$lbl)
        <button type="button" class="btn btn-sm {{ request('categorie',(string)request('categorie'))===$val ? ($val===''?'btn-secondary':'btn-primary') : ($val===''?'btn-outline-secondary':'btn-outline-primary') }}"
                onclick="document.querySelector('[name=categorie]').value='{{ $val }}';document.getElementById('modelesFilterForm').submit()">
            {{ $lbl }}
        </button>
        @endforeach
        <input type="hidden" name="categorie" value="{{ request('categorie') }}">
    </div>
</form>
<script>let _debounceT;function debounceSubmit(){clearTimeout(_debounceT);_debounceT=setTimeout(()=>document.getElementById('modelesFilterForm').submit(),600)}</script>
<div class="row" id="modelesGrid">@forelse($modeles as $modele)<div class="col-xl-3 col-lg-4 col-md-6 mb-4"><div class="card modele-card radius-10"><div class="card-body p-0"><div class="modele-photo-container">@if($modele->video_path)<video src="{{ asset('storage/'.$modele->video_path) }}" class="modele-photo" controls></video>@elseif($modele->photo_path)<img src="{{ asset('storage/'.$modele->photo_path) }}" class="modele-photo" alt="{{ $modele->nom }}">@else<div class="h-100 d-flex align-items-center justify-content-center"><i class="bx bx-t-shirt display-1 text-muted"></i></div>@endif<div class="modele-actions"><a href="{{ route('modeles.edit',$modele->id) }}" class="btn btn-sm btn-light" title="Modifier"><i class="bx bx-edit"></i></a><form action="{{ route('modeles.destroy',$modele->id) }}" method="POST" data-confirm="Supprimer ce modèle ?" data-confirm-text="Cette action est irréversible." data-confirm-btn="Supprimer">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-light" title="Supprimer"><i class="bx bx-trash"></i></button></form></div></div><div class="p-3"><h6 class="fw-bold mb-1">{{ $modele->nom ?: 'Modèle sans nom' }}</h6><p class="text-muted small mb-2">{{ $modele->description ?: 'Aucune description' }}</p><div class="d-flex justify-content-between align-items-center"><span class="fw-bold text-primary">{{ number_format($modele->prix ?? 0,0,',',' ') }} FCFA</span><span class="badge {{ ['ROBE'=>'bg-primary','JUPE'=>'bg-danger','HOMME'=>'bg-info','ENFANT'=>'bg-warning text-dark','AUTRE'=>'bg-secondary'][$modele->categorie] ?? 'bg-secondary' }}">{{ ['ROBE'=>'Robe','JUPE'=>'Jupe','HOMME'=>'Homme','ENFANT'=>'Enfant','AUTRE'=>'Autre'][$modele->categorie] ?? $modele->categorie }}</span></div></div></div></div></div>@empty<div class="col-12 text-center py-5"><i class="bx bx-t-shirt bx-lg text-muted mb-3"></i><h5 class="text-muted">Aucun modèle créé</h5><p class="text-muted">Commencez par créer votre premier modèle</p><a href="{{ route('modeles.create') }}" class="btn btn-primary"><i class="bx bx-plus me-1"></i>Créer un modèle</a></div>@endforelse</div><div class="d-flex justify-content-center">{{ $modeles->withQueryString()->links() }}</div>
@endsection
